defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.8.1-node

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys:
            - yarn-packages-{{checksum "yarn.lock"}}
      - run:
          name: "Build app"
          command: |
            yarn install
            PUBLIC_URL=/public yarn build;
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json

workflows:
  version: 2
  build:
    jobs:
      - build
